### ISSUE TITLE
Handle changes to the Guernsey Airport website

### ISSUE THREAD

**Issue by jasemagee** [jasemagee/data.gg#20]
New site will have proper feeds. Awaiting example data from Indulge. Due to be released mid of week starting 10th of May 2015

**Comment by jasemagee** [comment]
See commit. Had a best effort go at parsing the HTML an hour before bed. Bit concerned about dates as the new HTML feed has no date indicator. Hopefully this works tomorrow!

Could not locate the JSON/XML feed.

**Comment by adrianritchie** [comment]
The airport website has been switched over today to the new site and the data feed still appears to be working.
