### ISSUE TITLE
Font in Chome looks very diffrent to the one in  Firefox

### ISSUE THREAD

**Issue by jasemagee** [jasemagee/data.gg#22]
What is going on?!

**Comment by adrianritchie** [comment]
Are you sure it's not a browser cache issue?  This is Chrome 42.0.2311.135 (left) and Firefox Dev Edition 39.0a2 (right) on my machine:

![screen shot 2015-05-11 at 17 46 27](https://cloud.githubusercontent.com/assets/5040523/7570145/ba7b6c60-f805-11e4-9d66-d327c6dea585.png)

**Comment by jasemagee** [comment]
Looks fine on Windows to me. Think it has something to do with my local install of the Google Font on my Linux install...

**Comment by jasemagee** [comment]
Fail. This was my local machine. Installed a bolder version of the Google Font with the same name.
